# Site settings
title: Promotional Poster Design
description: This is a site
baseurl: "/information-architecture" # folder where your site lives, e.g. /web1-sp - needs to start with a slash

# Build settings
markdown: kramdown

defaults:  
  # settings for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "page"